# https://taskfile.dev
---
version: '3'

vars:
  PYTHON_VENVS_BASEDIR: ~/.venvs/
  PYTHON_VENV_DIR: "{{.PYTHON_VENVS_BASEDIR}}/docs"

tasks:
  start:
    desc: mkdocs serve docs
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        bash -c "
        source {{.PYTHON_VENV_DIR}}/bin/activate && \
            mkdocs serve -a localhost:8001
        "
