# https://taskfile.dev

version: '3'

vars:
  PYTHON_VENVS_BASEDIR: ~/.venvs/
  PYTHON_VENV_DIR_DOCS: "{{.PYTHON_VENVS_BASEDIR}}/docs"
  MKDOCS_PORT: 8001
  MKDOCS_BUILD_EXTRA_ARGS: ''

tasks:
  start:
    desc: mkdocs serve docs
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        bash -c "
        source {{.PYTHON_VENV_DIR_DOCS}}/bin/activate && \
            mkdocs serve -a localhost:{{.MKDOCS_PORT}}
        "

  build:
    desc: mkdocs build docs (strict, fails on warnings)
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        bash -c "
        source {{.PYTHON_VENV_DIR_DOCS}}/bin/activate && \
            mkdocs build --strict {{.MKDOCS_BUILD_EXTRA_ARGS}}
        "
